version: "3.8"
services:
  postgres:
    restart: always
    image: postgres:14

    shm_size: 1gb
    hostname: postgres
    container_name: la-cupula-postgres
    ports:
      - "5432:5432"
    networks:
      - default
    environment:
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
